# Generated by Django 5.2.7 on 2025-10-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bike_dock_reservado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='bike_serial_reservada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='codigo_desbloqueo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='hora_reserva',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
