# Generated by Django 5.2.7 on 2025-10-08 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('sancionado', 'Sancionado'), ('inactivo', 'Inactivo')], default='inactivo', max_length=15)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
