# Generated by Django 5.2.7 on 2025-10-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('electric', 'Eléctrica'), ('manual', 'Convencional')], max_length=20)),
                ('estado', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('maintenance', 'Mantenimiento'), ('unavailable', 'No disponible')], default='available', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bicicleta',
                'verbose_name_plural': 'Bicicletas',
            },
        ),
    ]
