# Generated by Django 5.2.7 on 2025-10-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bike_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bateria_porcentaje',
            field=models.PositiveIntegerField(default=100, help_text='Porcentaje de batería (solo para bicicletas eléctricas).'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('in_use', 'En uso'), ('maintenance', 'Mantenimiento'), ('unavailable', 'No disponible')], default='available', max_length=20),
        ),
    ]
