# Generated by Django 5.2.7 on 2025-10-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0002_wallet_created_at_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECARGA', 'Recarga de saldo'), ('PAGO', 'Pago de viaje o servicio'), ('REEMBOLSO', 'Reembolso'), ('PENALIDAD', 'Penalidad por uso indebido'), ('AJUSTE', 'Ajuste manual')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto positivo (RECARGA) o negativo (PAGO, etc.)', max_digits=12)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción libre de la transacción')),
                ('saldo_resultante', models.DecimalField(decimal_places=2, help_text='Saldo después de aplicar esta transacción', max_digits=12)),
                ('referencia_externa', models.CharField(blank=True, help_text='Ej: trip_id, payment_intent_id, etc.', max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transacción de Wallet',
                'verbose_name_plural': 'Transacciones de Wallet',
                'ordering': ['-creado_en'],
            },
        ),
    ]
