# Generated by Django 5.2.7 on 2025-11-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('operador', 'Operador de campo'), ('analista', 'Analista de datos'), ('soporte', 'Soporte técnico')], default='operador', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del administrador.', max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Determina si el administrador tiene acceso al panel.')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil de administrador.')),
                ('ultimo_acceso', models.DateTimeField(blank=True, help_text='Última fecha en que inició sesión en el panel.', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador del sistema',
                'verbose_name_plural': 'Administradores del sistema',
                'ordering': ['-creado_en'],
            },
        ),
    ]
