# Generated by Django 5.2.7 on 2025-11-06 00:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('no_devolucion', 'No devolvió la bicicleta'), ('daño_bicicleta', 'Daño al equipo o mal uso'), ('pago_pendiente', 'Pago pendiente'), ('comportamiento', 'Comportamiento inapropiado'), ('otros', 'Otros')], help_text='Motivo principal de la sanción.', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la falta o incidente.', null=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que inicia la sanción.')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha en que termina la sanción (si aplica).', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sanción sigue activa.')),
                ('creada_por', models.CharField(blank=True, help_text='Correo o nombre del administrador que aplicó la sanción.', max_length=100, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró la sanción.')),
                ('actualizada_en', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación de la sanción.')),
                ('usuario', models.ForeignKey(help_text='Usuario sancionado.', on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanción de usuario',
                'verbose_name_plural': 'Sanciones de usuarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
