# Generated by Django 5.2.7 on 2025-11-03 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('battery', models.FloatField(help_text='Porcentaje de batería (0–100%)')),
                ('lock_status', models.CharField(choices=[('LOCKED', 'Candado cerrado'), ('UNLOCKED', 'Candado abierto')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telemetría de Bicicleta',
                'verbose_name_plural': 'Telemetrías de Bicicletas',
                'ordering': ['-received_at'],
            },
        ),
    ]
